apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonar-data2
  labels:
    type: sonar-data2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonar-data2    # <--- Use a new, empty directory
  persistentVolumeReclaimPolicy: Retain
