apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonar-data
  annotation:
    give: five
  labels:
    type: sonar-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonar-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonar-ext
  labels:
    type: sonar-ext
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonar-ext
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonar-logs
  labels:
    type: sonar-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonar-logs
  persistentVolumeReclaimPolicy: Retain
