apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data2-pvc
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      type: sonar-data2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

