apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-pvc
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      type: sonar-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-ext-pvc
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      type: sonar-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-logs-pvc
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      type: sonar-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

