apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:10.5-community
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://sonar-postgres-0.sonar-postgres-headless.sonarqube.svc.cluster.local:5432/sonar
        - name: SONAR_JDBC_USERNAME
          value: sonar
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - mountPath: /opt/sonarqube/data
          name: sonar-data
        - mountPath: /opt/sonarqube/extensions
          name: sonar-extensions
        - mountPath: /opt/sonarqube/logs
          name: sonar-logs
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data2-pvc
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-ext-pvc
      - name: sonar-logs
        persistentVolumeClaim:
          claimName: sonar-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: sonarqube
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30090
  selector:
    app: sonarqube
